"""
Collection of standard types used through the application.

These types can be aliases for intent clarify or wrappers
around common types.

For more application specific types, see models.
"""
from datetime import datetime, timedelta, timezone, UTC
import secrets
from typing import Callable, NewType, TypeAlias, Self, TypeVar
from uuid import UUID

from attrs import define, field


# region @types.std
# ---
# role: datatype
# intent: alias standard types for typechecking clarity.
# description: >
#   SchemaVersion: opaque string that carries a semantic-version tag for
#   serialized payloads, preventing silent schema mismatches.
#   JsonAtom: leaf-level JSON scalar (None | bool | int | float | str).
#   JsonData: fully recursive JSON value type used at serialisation boundaries.
# rules:
#   - Not used for application specific models. See models.
# dependencies:
# aliases:
#   - json
#   - schema version
# triggers:
#   - what is JsonData
#   - how is schema version typed
# ---

SchemaVersion = NewType("SchemaVersion", str)
JsonAtom: TypeAlias = None | bool | int | float | str
JsonData: TypeAlias =  JsonAtom | dict[str, "JsonData"] | list["JsonData"]

# ---
# endregion

# region @types.time
# ---
# role: datatype
# intent: UTC-aware time primitives and their UUIDv7 representations
# description: >
#   Timestamp wraps datetime, enforces UTC, and is the single source of truth
#   for wall-clock time. Period is an optional [start, end] Timestamp range.
#   PeriodUUID is the UUIDv7-encoded form of Period used as a query key in
#   storage paths and database range scans.
#   Primary conversion API — Timestamp.to_uuid() / Timestamp.from_uuid() —
#   uses standard UUIDv7 (RFC 9562, ascending lexicographic ordering, so a
#   newer timestamp maps to a larger UUID value).
# rules:
#   - Timestamps MUST be timezone-aware and MUST be in UTC.
#   - to_uuid / from_uuid MUST use standard UUIDv7 (ascending ordering).
#   - PeriodUUID MUST only be constructed from UUIDv7 values.
#   - Period.covers() compares datetime values; PeriodUUID.covers() compares UUID values.
# dependencies:
# aliases:
#   - timestamp
#   - period
#   - period uuid
# triggers:
#   - how to convert a timestamp to a UUID
#   - what is PeriodUUID
#   - how does covers work
#   - how to filter runs by time range
# ---

@define(slots=True)
class Timestamp:
    """
    Immutable timestamp wrapper with timezone awareness.

    All timestamps are stored in UTC for consistency.
    """
    value: datetime = field()

    @value.validator
    def check(self, _, value):
        if not isinstance(value, datetime):
            raise TypeError("Must be a datetime")
        if value.tzinfo is not UTC:
            raise ValueError("datetime must have tzinfo=UTC")

    @classmethod
    def now(cls) -> Self:
        """Get current UTC timestamp."""
        return cls(datetime.now(timezone.utc))

    @classmethod
    def from_datetime(cls, dt: datetime) -> Self:
        """Create from datetime, converting to UTC if needed."""
        if dt.tzinfo is None:
            # Assume UTC if no timezone specified
            dt = dt.replace(tzinfo=timezone.utc)
        else:
            # Convert to UTC
            dt = dt.astimezone(timezone.utc)
        return cls(dt)

    @classmethod
    def from_iso(cls, iso_string: str) -> Self:
        """Parse from ISO 8601 format string."""
        dt = datetime.fromisoformat(iso_string)
        return cls.from_datetime(dt)

    def to_iso(self) -> str:
        """Convert to ISO 8601 format string."""
        return self.value.isoformat()

    @classmethod
    def from_uuid7(cls, u: UUID) -> Self:
        """Extract timestamp from a standard UUIDv7.

        Args:
            u: A standard UUIDv7.

        Returns:
            The Timestamp embedded in the UUID.
        """
        if u.version != 7:
            raise ValueError("Not a UUIDv7")
        # Top 48 bits = Unix timestamp in milliseconds
        ts_ms = (u.int >> 80) & 0xFFFF_FFFF_FFFF
        return cls(datetime.fromtimestamp(ts_ms / 1000, tz=UTC))

    @classmethod
    def from_uuid(cls, u: UUID) -> Self:
        """Extract timestamp from a standard UUIDv7.

        Convenience alias for from_uuid7.

        Args:
            u: A UUIDv7 (e.g. generated by Timestamp.to_uuid()).

        Returns:
            The Timestamp embedded in the UUID.
        """
        return cls.from_uuid7(u)

    def to_uuid7(self) -> UUID:
        """Convert to a standard UUIDv7 (RFC 9562, ascending lexicographic order).

        Layout (128 bits):
            127..80  unix_ts_ms  48-bit millisecond timestamp
             79..76  0x7         version
             75..64  rand_a      12 random bits
             63..62  0b10        RFC 4122 variant
             61..0   rand_b      62 random bits
        """
        ts_ms  = int(self.value.timestamp() * 1000)
        rand_a = secrets.randbits(12)
        rand_b = secrets.randbits(62)
        return UUID(int=(
              (ts_ms  << 80)
            | (0x7    << 76)
            | (rand_a << 64)
            | (0b10   << 62)
            |  rand_b
        ))

    def to_uuid(self) -> UUID:
        """Convert to a standard UUIDv7 (ascending ordering).

        Convenience alias for to_uuid7.

        Returns:
            A UUIDv7 embedding this timestamp.
        """
        return self.to_uuid7()

    def __str__(self) -> str:
        """String representation in ISO format."""
        return self.to_iso()

    def __repr__(self) -> str:
        """Developer-friendly representation."""
        return f"Timestamp({self.to_iso()})"


@define
class Period:
    """Optional [start, end] wall-clock time range.

    Both bounds are inclusive-open (covers() uses strict inequalities).
    Either bound may be None to represent an open interval.
    Convert to PeriodUUID with to_uuid() for use as a storage query key.
    """

    start: Timestamp | None = field(default=None)
    end: Timestamp | None = field(default=None)

    def duration(self) -> timedelta | None:
        if self.start is None or self.end is None:
            return None
        return self.end.value - self.start.value

    def to_uuid(self) -> PeriodUUID:
        """Convert to a PeriodUUID using standard UUIDv7 encoding."""
        return PeriodUUID(
            start=self.start.to_uuid() if self.start is not None else None,
            end=self.end.to_uuid() if self.end is not None else None,
        )

    def covers(self, ts: Timestamp) -> bool:
        return (
            (self.start is None or ts.value > self.start.value)
            and (self.end is None or ts.value < self.end.value)
        )


@define
class PeriodUUID:
    """A time range encoded as a pair of standard UUIDv7 values.

    Used as a compact, lexicographically sortable query key in storage paths
    and database range scans.  UUIDv7 embeds the millisecond timestamp in its
    top 48 bits, so UUID ordering equals chronological ordering.

    Construct from a Period with Period.to_uuid(), or parse the
    ``<start>--<end>`` string representation with from_str().
    Convert back to wall-clock time with to_timestamp().
    """

    start: UUID | None = field(default=None)
    end: UUID | None = field(default=None)

    @classmethod
    def from_str(cls, value) -> Self:
        parts = value.split("--")
        if len(parts) != 2:
            raise ValueError(f"Invalid PeriodUUID {value}: MUST follow the format <start_uuid>--<end_uuid>")
        start = UUID(parts[0])
        end = UUID(parts[1])
        return cls(start=start, end=end)

    def __str__(self) -> str:
        return f"{self.start}--{self.end}"

    def to_timestamp(self) -> Period:
        """Convert to a Period by extracting timestamps from the UUIDv7 bounds."""
        return Period(
            start=Timestamp.from_uuid(self.start) if self.start is not None else None,
            end=Timestamp.from_uuid(self.end) if self.end is not None else None,
        )

    def covers(self, uid: UUID) -> bool:
        """Return True if uid falls within this period.

        UUIDv7 ordering equals chronological ordering, so this mirrors
        Period.covers(): strictly inside the (start, end) interval, with
        None meaning an open bound.
        """
        return (
            (self.start is None or uid > self.start)
            and (self.end is None or uid < self.end)
        )

# ---
# endregion


T = TypeVar("T")
R = TypeVar("R")
def map_or_none(value: T | None, func: Callable[[T], R]) -> R | None:
    return func(value) if value is not None else None
